### ISSUE TITLE
Levels don't work

### ISSUE THREAD

**Issue by AliAlhakeem** [Radfordhound/SLW-Mod-Loader#10]
i don't know why but the levels don't work
just the characters
and i have a cracked version :P
So... can you help me

**Comment by GoldtexTwitch** [comment]
This mod loader doesn't work with cracked versions.

**Comment by Radfordhound** [comment]
Yeah.. sounds like a bug related to the game not being loaded through Steam (since you're using a pirated copy).

Apologies, but the mod loader does not officially support cracked copies of the game. I mean no dis-respect to you, but it is (quite simply) a law, and one that I wish not to break. Please see #7 for more details. Thank you.
