### ISSUE TITLE
Reguest a feature 

### ISSUE THREAD

**Issue by Silverdash1994** [Radfordhound/SLW-Mod-Loader#13]
Unlimited rings for Sonic lost world mod loader

**Comment by GoldtexTwitch** [comment]
This is something that would fit more into a Sonic Lost World trainer than a mod loader for Sonic Lost World.

**Comment by Radfordhound** [comment]
That's definitely a cool suggestion, but it's more of a memory-editing kind of thing as Goldtex mentioned and I don't necessarily feel it fits into the mod loader.

I'm closing this issue for now simply because I feel that while it's definitely a nice idea, it doesn't quite fit into the rest of the program. If you'd like to further discuss this suggestion, feel free to re-open the issue!
