### ISSUE TITLE
Not sure what this is

### ISSUE THREAD

**Issue by BiggieCheese64** [Radfordhound/SLW-Mod-Loader#19]
Ive downloaded the mod loader and placed it in the correct location, ive disabled any antiviruses and have bought the game legitimatelly. however the game now wont come on whenever i press play on the steam app, the exe file, or even through the ,modloader. Im up to the latest build and have reinstalled the game to make sure everything works. but nothing does. effectively making my game useless.

**Comment by thesupersonic16** [comment]
Make sure you use the latest release (5.3), And Don't build the newest source as the rewrite isn't finished.
Can you also please upload slw.exe to a site like Google Drive and send a link here so we can take a look at it.

**Comment by Radfordhound** [comment]
Hey! Sorry to hear you're having trouble! Honestly I'm not sure what's going on, the mod loader makes an edit to the game's executable to enable mod loading, but that's all it does to the actual game. Simply reinstalling the game should fix that, so I'm surprised to see reinstalling didn't seem to fix the problem.

I wonder if this issue is being caused by something else other than the mod loader? I'm sorry, I honestly have no idea..
