### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by hinhin0611** [Radfordhound/SLW-Mod-Loader#2]
Can you make non legally-purchase also can load the mods?

**Comment by Radfordhound** [comment]
Thank you for your request, and apologies for the inconvenience, but I don't support piracy. There are ways to get it to work that I'm sure you'll find if you tinker around with the mod loader's code (or even just certain files released with a binary version), though I will not officially disclose these due to both legal and moral values I wish not to violate. Thank you for understanding.
