### ISSUE TITLE
Can't launch the program (4.x)

### ISSUE THREAD

**Issue by ShadeVortex** [Radfordhound/SLW-Mod-Loader#6]
I hadn't upgraded this version since 1.4, but I tried upgrading the program and the 4.x versions have been completely broken for me. They launch (multiple times) in the task manager but the program never opens.

It'll "load" for a while, but never do anything. It also causes Steam and Explorer to crash. I'm on Windows 7 64-bit. For the rest of my specs, you can see them on this list: http://pcpartpicker.com/user/ShadeVortex/saved/qYbKHx

**Comment by Radfordhound** [comment]
Hang on... so you start the program by double-clicking on the compiled executable (SLWModLoader.exe) once, and it opens multiple times in task manager, crashes Steam/Windows Explorer, and never actually appears?!? O.O

Uh... sorry to hear about this, man! :| Thanks for letting me know! Do the 3.x/2.x versions work any differently/at all? Or are they broken, too?

**Comment by ShadeVortex** [comment]
Seems like 2.1 is the latest version that will work for me. I've also seemingly tracked the problem down to cpkredir itself, because I tried just switching to using that by itself and even trying to install it with its installer led to the same problems I'm having with this program. Looks like I have to hope Korama can fix this issue, then.

**Comment by Radfordhound** [comment]
Sorry to hear about that! :( Hope you can get it fixed! Apologies for not being very helpful.. it's just that without the CPKREDIR source I don't really have any idea as to what could be causing this. :/

I'm closing this issue for now since it seems to not be related directly to the mod loader, though please feel free to re-open it if needed! ;)
