### ISSUE TITLE
why doesnt the mod loader work with a cracked version?sonic gmi worked

### ISSUE THREAD

**Issue by JSSA2000** [Radfordhound/SLW-Mod-Loader#7]

**Comment by Radfordhound** [comment]
SonicGMI and SLW Mod Loader are two separate programs developed by two separate people. SonicGMI by Dario, and SLW Mod Loader by myself.

SonicGMI did not take people pirating copies of the game into account (since no one considered the fact that anyone would even try to do so in the first place), and as such, worked correctly with pirated copies. However, as a result of this, a huge amount of Generations copies were illegally downloaded by those un-willing to pay a few dollars to play the game, and SEGA lost a lot of money they would have earned otherwise.

Because of this, now that Lost World has released, I (when developing the mod loader) decided to require a legally-purchased version of the game in order to prevent the same thing from happening again like it did with SonicGMI.

Honestly, no offense, but isn't the reason obvious? **Piracy is highly illegal!** It's really as simple as that.

The game's literally $30 (actually, it's $14.99 for the time being due to a Steam holiday sale.. so it's not even that!). Why not just pick up a copy? Even if you don't end up particularly enjoying the game, it still shows SEGA that we want more PC ports of Sonic games in the future, so it's basically a win-win.

I'm closing this issue for now. If you'd like to further discuss it, please feel free to re-open it. Thank you.

**Comment by JSSA2000** [comment]
isn't there any way to make the mod loader work with it? im thinking on buying a copy of slw but im currently saving for a new processor so the game can run at 60 fps. I've already did some texture hacks and i wanna test them and maybe release them to the public but i cant do that when the mod loader doesnt work. :(

**Comment by Radfordhound** [comment]
I'm sorry, but no. Not really. Piracy is illegal and I wish not to support it. Again, sorry if I come off as rude here, but it's as simple as that.

If you'd really like to use a cracked version, that's your decision and I won't judge you for it. But if that's the way you'd like to fly, you'll have to edit the code to the mod loader (which is sitting right here on GitHub, btw) by yourself since I'm not going to officially support it. Again, I'm sorry, but I'm not going to spend time updating the mod loader just so people can play the game modded without paying for it.

I will, however, test your texture mods for you to confirm that they work/don't work so you can release them, so long as you're comfortable with sending them to me.

**Comment by JSSA2000** [comment]
​
 Negative Sonic.rar <https://mail.google.com/mail/u/1/undefined>
​sent you the texture mods since you said you could test them for me

2016-01-11 15:31 GMT-08:00 Radfordhound <notifications@github.com>:

**Comment by Radfordhound** [comment]
Apologies, but that link just brings up my GMail with no link attached for me. :| Could you maybe try either:

A: Dragging and dropping that file onto the text box you type into when replying to an issue (not via E-Mail, but from the actual GitHub site) that says "Attach files by dragging & dropping" towards the bottom of it.

B: Throwing that file onto something like [Dropbox](https://www.dropbox.com), then giving me the link you get to it when right-clicking on it and choosing "Share."

C: Replying to this via your E-Mail address and attaching the file to the E-Mail.

Sorry for the inconvenience/delayed response, and thank you for sending the file in advance :)

**Comment by Krigeris** [comment]
I've already bought this game multiple times; for the dreamcast and for the gamecube. You are an elitist dickhead for doing this shit.

**Comment by Levi-501** [comment]
> I'm sorry, but no. Not really. Piracy is illegal and I wish not to support it. Again, sorry if I come off as rude here, but it's as simple as that.
> 
> If you'd really like to use a cracked version, that's your decision and I won't judge you for it. But if that's the way you'd like to fly, you'll have to edit the code to the mod loader (which is sitting right here on GitHub, btw) by yourself since I'm not going to officially support it. Again, I'm sorry, but I'm not going to spend time updating the mod loader just so people can play the game modded without paying for it.
> 
> I will, however, test your texture mods for you to confirm that they work/don't work so you can release them, so long as you're comfortable with sending them to me.

Im sorry but yes, you came off as a total duche bag even though it was a reply to someone else.  Not our fault everyone can wipe their ass  with their money reguardless of it being $20 or so!!  Not only that but other issues tend to happen like maybe it didn't run right on PC or just didn't like gameplay.
